# Generated by Django 3.0 on 2020-02-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleproject', '0004_auto_20200104_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(upload_to='media/image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(upload_to='media/image'),
        ),
    ]
